### PR TITLE
Setup sbt project

### PR DESCRIPTION
**Pull request by josephharfouch**
Hi Andrew 
This turned out to be quite easy so far, so my incremental approach in hindsight was probably an overkill, but no harm done. A trivial build.sbt and sbt package command produces the jar for us (much nicer than the ant build.xml file). Next, I think I will modify that version_athanor program that I wrote so that it versions the cpp dll rather than the jar, then I can get you to put this for me in nlytx, and I can then try to pull that dependency down. Let me know if there is a problem with this approach.

### CODE REVIEW

**Comment by andrewresearch** [comment]
Thought I'd let you discover that for yourself :-)
Probably best to reference the native dependencies directly. Did you take a look at the JNI SBT link and also the nlytx-nlp option for publishing the final jar?

**Comment by andrewresearch** [comment]
BTW, the publishing process will use the name and version from SBT, so let's use the project name `athanor4s` and start with a pre-release version `0.1.0`. Once we have a release version we can bump it to `1.0.0`.

**Comment by josephharfouch** [comment]
I will fix the project name and release version 0.1.0. 

I had a look at the JNI SBTlink, but I am not sure I understand it yet, and I thought I will play with it once the cpp dll dependency is in nlytx, and this why I thought I will produce a versioned copy of it next  (I am assuming I need that to test the JNI sbt link but maybe I am missing something here). I am actually wondering why we need something special for JNI because I thought sbt will just put the .so dll for us in the right place once we supply a resolver and it should work, but I haven't played with this before.  

I thought I will leave the jar publishing from athanor4s and the nlytx-nltp for last. Does your arguments about copyright issue differences apply to the athanor4s interface as well as athanor? If not, then I think setting up a project dependency with atanor-server and athanor4s should work without doing anything special and publishing any jars (sbt would not pull any athanor source files but it will pull the two java files, the cpp dll and the rest of the athanor project into an sbt hidden  directory) .

**Comment by andrewresearch** [comment]
What do you mean by cpp dll dependency is in nlytx? We shouldn't put any of the C++ binaries in BinTray. The final JAR will be published to BinTray.
JNI allows us to build the interface between Java and C++, or in our case Scala and C++. 
SBT should only pull in the necessary JNI dependencies for this project. The Athanor dependencies we will manually add to the appropriate directories to enable dynamic loading. These directories will need to be flagged to SBT for the build process to ensure the files are incorporated in the JAR.
There is no need to incorporate the other Athanor project as the libatanor.so files are all that we need from Athanor. Everything else is the interface between Scala and the runtime selected version of libatanor.

**Comment by josephharfouch** [comment]
Hi Andrew,

I am quite confused at the moment, because right now everything seems to
work and the only issue is how to get the .so dll from athanor to
athanor4s.
I will study the examples you gave me in more depth and read about sbt
jni dependencies. If I am completely stuck, we may be we can do a
telephone chat tomorrow or Friday, but I better do more reading first.
--
Joseph Harfouch
joseph@harfouch.id.au
using fastmail


On Wed, Nov 15, 2017, at 01:28 PM, Andrew Gibson wrote:
> What do you mean by cpp dll dependency is in nlytx? We shouldn't put
> any of the C++ binaries in BinTray. The final JAR will be published to
> BinTray.>  JNI allows us to build the interface between Java and C++, or in our
>  case Scala and C++.>  SBT should only pull in the necessary JNI dependencies for this
>  project. The Athanor dependencies we will manually add to the
>  appropriate directories to enable dynamic loading. These directories
>  will need to be flagged to SBT for the build process to ensure the
>  files are incorporated in the JAR.>  There is no need to incorporate the other Athanor project as the
>  libatanor.so files are all that we need from Athanor. Everything else
>  is the interface between Scala and the runtime selected version of
>  libatanor.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/uts-cic/athanor4s/pull/3#issuecomment-344490068

**Pull request merged**
